apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
        - name: scaletestapp-container
          image: pitver/service-a:latest
          resources:
            requests:
              memory: "150Mi"  # Минимальный запрос памяти
              cpu: "300m"
            limits:
              memory: "200Mi"  # Лимит памяти
              cpu: "400m"
          ports:
            - containerPort: 80
