@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()
title Контейнерная диаграмма экосистемы умного дома

' Определение контейнеров
Boundary(CB_API, "API Gateway") {
    Container(C_API, "API Gateway", "Gateway", "Управляет входящими запросами и маршрутизацией")
}

Container(C_Device_Management, "Device Management & Registration Service", "Java/Spring Boot", "Управление устройствами и их регистрация")
Container(C_Automation, "Automation Service", "Java/Spring Boot", "Обработка сценариев автоматизации")
Container(C_Monitoring, "Monitoring Service", "Java/Spring Boot", "Мониторинг состояния устройств")
Container(C_User_Management, "User & Access Control Management Service", "Java/Spring Boot", "Управление пользователями и доступом")
Container(C_Device_Integration, "Device Integration Service", "Java/Spring Boot", "Интеграция с внешними устройствами")

ContainerDb(DB_User, "User & Access Control Database", "PostgreSQL", "База данных пользователей и управления доступом")
ContainerDb(DB_Device, "Device Database", "PostgreSQL", "База данных устройств")
Queue "Kafka", "Message Broker", "Шина данных для обмена сообщениями"

' Определение внешних систем
System_Ext(User, "Пользователь", "Пользователь веб-интерфейса")
System_Ext(Device, "Устройство", "Интеллектуальные устройства")

' Определение связей
Rel(User, C_API, "Запросы на управление и мониторинг")
Rel(C_API, C_Device_Management, "Запросы управления и регистрации устройств")
Rel(C_API, C_Automation, "Запросы автоматизации")
Rel(C_API, C_Monitoring, "Запросы мониторинга")
Rel(C_API, C_User_Management, "Запросы управления пользователями и доступом")
Rel(C_API, C_Device_Integration, "Запросы интеграции устройств")

Rel(C_Monitoring, Kafka, "Публикация данных датчиков")
Rel(Kafka, C_Automation, "Подписка на данные датчиков")
Rel(C_Device_Integration, Kafka, "Публикация данных устройств")
Rel(C_Device_Integration, C_Device_Management, "Данные и команды устройств")
Rel(C_Device_Management, DB_Device, "Чтение и запись данных об устройствах")
Rel(C_User_Management, DB_User, "Чтение и запись данных пользователей и прав доступа")
Rel(C_Automation, C_Device_Management, "Отправка команд для управления устройствами")

Rel(Device, C_Device_Integration, "Данные и команды устройств")
@enduml