apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configurer-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: config-user
    namespace: default
roleRef:
  kind: Role
  name: configurer
  apiGroup: rbac.authorization.k8s.io