apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-management
  template:
    metadata:
      labels:
        app: device-management
    spec:
      containers:
        - name: device-management
          image: pitver/device-management:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: device-management
spec:
  ports:
    - port: 8081
  selector:
    app: device-management
