apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "2.1"
    consumers:
      - username: user
        jwt_secrets:
          - key: user
            secret: "123"
    services:
      - name: device-management
        url: http://device-management:8081
        routes:
          - name: device-route
            paths:
              - /device
            strip_path: true
            plugins:
              - name: jwt
                config:
                  run_on_preflight: true
                  key_claim_name: iss
      - name: telemetry-management
        url: http://telemetry-management:8082
        routes:
          - name: telemetry-route
            paths:
              - /telemetry
            strip_path: true
            plugins:
              - name: jwt
                config:
                  run_on_preflight: true
                  key_claim_name: iss
